### ISSUE TITLE
ImportError: cannot import name 'region' from 'get_mask.utils.pyvotkit' 

### ISSUE THREAD

**Issue by AskingATonOfQuestions** [zllrunning/video-object-removal#10]
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    from mask import mask
  File "C:\Users\Admin\vor\mask.py", line 8, in <module>
    from get_mask.test import *
  File "C:\Users\Admin\vor\get_mask\test.py", line 30, in <module>
    from get_mask.utils.pyvotkit.region import vot_overlap, vot_float2str
  File "C:\Users\Admin\vor\get_mask\utils\pyvotkit\__init__.py", line 9, in <module>
    from . import region
ImportError: cannot import name 'region' from 'get_mask.utils.pyvotkit' (C:\Users\Admin\vor\get_mask\utils\pyvotkit\__init__.py)

**Comment by sagar1garg** [comment]
@KSimoncikas what is the solution for this error? I am getting the same.

**Comment by JeetShah25** [comment]
What is the solution?? getting the same error.. Please help

**Comment by ulatekh** [comment]
Use python3 instead of python (which is probably major-version 2).

**Comment by outfielder** [comment]
For anyone else getting this issue - I went from Python version 3.7 to Python verison 3.6 and it fixed the error.

**Comment by arnavmehta7** [comment]
😭 How to fix?
