### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IICommitII** [zllrunning/video-object-removal#3]
Excellent work here. I am confused about the licensing implications though. Would help if you could clarify if this can be used commercially? 

Thanks!

**Comment by notpushkin** [comment]
@zllrunning I would suggest either [ISC] or [AGPL-3.0], whatever you prefer. Tl;dr: ISC just requires to name you as the author (and perhaps you might also want require to cite the papers your code is based on) while AGPL also requires the (modified) source code to be provided to end users.

And thanks for the project, really impressive work!

[ISC]: https://choosealicense.com/licenses/isc/
[AGPL-3.0]: https://choosealicense.com/licenses/agpl-3.0/

**Comment by zllrunning** [comment]
Thanks for your interest. Licensed under an MIT license.
