### ISSUE TITLE
from . import region

### ISSUE THREAD

**Issue by Sauman9456** [zllrunning/video-object-removal#7]
from . import region
ImportError: cannot import name 'region' from 'get_mask.utils.pyvotkit' (F:\Downloads\idm\Compressed\video-object-removal-master\video-object-removal-master\get_mask\utils\pyvotkit\__init__.py)

**Comment by sagar1garg** [comment]
@Sauman9456 what's the solution for this error? I am getting the same error.

**Comment by outfielder** [comment]
For anyone else getting this issue - I went from Python version 3.7 to Python verison 3.6 and it fixed the error.
